#include "../include/setdriver.h"


int main(int argc, const char ** argv){
    struct _cset *c, *c2, *c3, *c4;
    struct _iset *i,*i2, *i3, *i4;
    c = create_cset(10);
    i = create_iset(10);
    c2 = create_cset(10);
    i2 = create_iset(10);
    display_set(c,1);
    display_set(i,0);
    display_set(c2,1);
    display_set(i2,0);
    add_to_cset(c,'r');
    add_to_cset(c,'q');
    add_to_cset(c,'7');
    add_to_cset(c2,'0');
    add_to_cset(c,'5');
    add_to_cset(c2,2+'0');
    add_to_cset(c2,'b');
    add_to_iset(i,-4);
    add_to_iset(i,69);
    add_to_iset(i2,79);
    add_to_iset(i2,69);
    add_to_iset(i2,89);
    add_to_iset(i2,1009);
    display_set(c,1);
    display_set(i,0);
    display_set(c2,1);
    display_set(i2,0);
    c3 = merge_sets(c2,c,1);
    printf("c3\n");
    display_set(c3,1);
    printf("c2\n");
    display_set(c2,1);
    printf("c1\n");
    display_set(c,1);
    add_to_cset(c2,'.');
    printf("c3\n");
    display_set(c3,1);
    printf("c2\n");
    display_set(c2,1);
    printf("c1\n");
    display_set(c,1);
    c4 = copy_cset(c3);
    add_to_cset(c4,'S');
    display_set(c3,1);
    display_set(c4,1);
    printf("is in set %d\n", is_in_cset(c4,'5'));
    printf("is in set %d\n", is_in_cset(c4,'S'));
    printf("is in set %d\n", is_in_cset(c4,'s'));
    printf("is in set %d\n", is_in_cset(c4,'a'));
    printf("is in i set %d\n", is_in_iset(i2,2));
    printf("is in i set %d\n", is_in_iset(i2,89));
    printf("is in i set %d\n", is_in_iset(i2,1009));
    i3 = merge_isets(i,i2);
    i4 = copy_iset(i3);
    add_to_iset(i4,-420);
    display_set(i,0);
    display_set(i2,0);
    display_set(i3,0);
    display_set(i4,0);
    delete_set(c,1);
    delete_set(i,0);
    delete_set(c2,1);
    delete_set(i2,0);
    delete_set(i3,1);
    delete_set(c3,1);
    delete_set(c4,1);
    delete_set(i4,1);
    c = NULL;
    i = NULL;
    i3 = NULL;
    c2 = NULL;
    i2 = NULL;
    c3 = NULL;
    c4 = NULL;
    i4 = NULL;
	return 0;
}
